### ISSUE TITLE
Error: Invalid cache option true found. 

### ISSUE THREAD

**Issue by yangsibai** [yangsibai/simple-mvc#2]
```
Error: Invalid cache option true found. Expected "memory" or { get: function (key) { ... }, set: function (key, value) { ... } }.
    at validateOptions (/srv/mockup/node_modules/swig/lib/swig.js:113:15)
    at parse (/srv/mockup/node_modules/swig/lib/swig.js:334:5)
    at Object.precompile (/srv/mockup/node_modules/swig/lib/swig.js:479:23)
    at Object.compile (/srv/mockup/node_modules/swig/lib/swig.js:584:16)
    at Function.exports.swig.render (/srv/mockup/node_modules/simple-mvc/node_modules/consolidate/lib/consolidate.js:246:56)
    at /srv/mockup/node_modules/simple-mvc/node_modules/consolidate/lib/consolidate.js:146:25
    at read (/srv/mockup/node_modules/simple-mvc/node_modules/consolidate/lib/consolidate.js:91:22)
    at /srv/mockup/node_modules/simple-mvc/node_modules/consolidate/lib/consolidate.js:144:9
    at readPartials (/srv/mockup/node_modules/simple-mvc/node_modules/consolidate/lib/consolidate.js:114:33)
    at View.engine (/srv/mockup/node_modules/simple-mvc/node_modules/consolidate/lib/consolidate.js:139:5)
```

**Comment by yangsibai** [comment]
Update `consolidate` to `0.15.1` can fix this problem.
